added support for union types
charlypoly/graphql-to-json-schema pull request #36
Opened 2021-07-16 18:57 UTC by newhouse

2021-07-20 15:13 UTC, newhouse commented
bump @charlypoly 😄

2021-07-20 15:14 UTC, newhouse commented on lib/reducer.ts
> +      anyOf: curr.possibleTypes.map((type) => graphqlToJSONType(type, options)),
Unless this should be `oneOf`?

2021-07-20 15:24 UTC, charlypoly commented on lib/reducer.ts
> +      anyOf: curr.possibleTypes.map((type) => graphqlToJSONType(type, options)),
@newhouse yes, this should be a `oneOf`

2021-07-20 15:25 UTC, charlypoly requested changes
`anyOf` ➡️ `oneOf`

2021-07-20 21:18 UTC, newhouse commented
> `anyOf` ➡️ `oneOf`

Updated @charlypoly

2021-07-21 07:00 UTC, charlypoly approved these changes

2021-07-21 07:00 UTC, merged

2021-07-21 07:01 UTC, charlypoly commented
Thanks @newhouse ! 🙇🏼

2021-07-21 07:04 UTC, charlypoly commented
Published in `graphql-2-json-schema@0.7.0` 🚢